### ISSUE TITLE
umitag.py NameError: global name 'read1_in' is not defined

### ISSUE THREAD

**Issue by apastore** [aryeelab/umi#11]
I what to test umm, but I get NameError: global name 'read1_in' is not defined with this command (all test in the data folder are OK)

python ../umitag.py --read1_in mysample.r1.fastq --read2_in mysample.r2.fastq --read1_out mysample.r1.umitagged.fastq --read2_out mysample.r2.umitagged.fastq --index1 mysample.i1.fastq --index2 mysample.i2.fastq

Traceback (most recent call last):
  File "/Users/alessandro/umi/umitag.py", line 95, in <module>
    main()
  File "/Users/alessandro/umi/umitag.py", line 92, in main
    umitag(read1_in, read2_in, index1, index2, read1_out, read2_out, out_dir)
NameError: global name 'read1_in' is not defined

**Comment by apastore** [comment]
line 92 gf umitag.py have to say 
umitag(args['read1_in'], args['read2_in'], args['index1'], args['index2'], args['read1_out'], args['read2_out'], args['out_dir'])

**Comment by martinaryee** [comment]
Thanks for catching this. Feel free to submit a pull request. Otherwise I should be able to fix in the next day or two.
